MehVahdJukaar/Supplementaries

src/main/java/net/mehvahdjukaar/supplementaries/block/tiles/OilLanternBlockTile.java
Copper, brass and crimson lanterns respect the fast_lanterns configuration option for consistency with other lanterns.
=> Make Copper, Brass and Crimson Lanterns respect the fast_lanterns config option.

build.gradle, src/main/java/net/mehvahdjukaar/supplementaries/common/block/tiles/JarBlockTile.java
Changes isPonyJar() to accept any arbitrary casing of "cum". Degeneracy should be available to all, regardless of capitalization.
=> Improve Cum Check

src/main/resources/supplementaries.mixins.json
Fixes this being spammed by the log 
```
[Server thread/DEBUG] [mixin/]: supplementaries.mixins.json:ChunkHolderMixin: Class version 61 required is higher than the class version supported by the current version of Mixin (JAVA_16 supports class version 60)
```
=> Updates Mixin Compatibility Level to Java 17

common/src/main/java/net/mehvahdjukaar/supplementaries/common/block/tiles/FrameBlockTile.java, common/src/main/java/net/mehvahdjukaar/supplementaries/reg/ModTags.java
Some blocks, when framed can cause rendering issues as well as not all immovable blocks can feasibly be accounted for so adding a tag would allow for mod developers and or mod pack developers to fix this themselves.
Example Rendering Issue When Framing What Is Currently A "Valid" Block (From Timber Frames Mod)
=> Add A Tag To Prevent A Block From Being Framed

common/src/main/java/net/mehvahdjukaar/supplementaries/common/block/dispenser/DispenserBehaviorsManager.java
Changed "Error white" to "Error while"
=> Fix typo in Dispenser Manager error log

common/src/main/java/net/mehvahdjukaar/supplementaries/Supplementaries.java, common/src/main/java/net/mehvahdjukaar/supplementaries/reg/ModArguments.java, common/src/main/resources/assets/supplementaries/lang/en_us.json, common/src/main/resources/assets/supplementaries/lang/zh_cn.json, common/src/main/resources/assets/supplementaries/lang/zh_tw.json, fabric/src/main/java/net/mehvahdjukaar/supplementaries/common/commands/arguments/fabric/NoteBlockInstrumentArgument.java, fabric/src/main/java/net/mehvahdjukaar/supplementaries/common/commands/arguments/fabric/SourceArgument.java, fabric/src/main/java/net/mehvahdjukaar/supplementaries/common/commands/fabric/RecordSongCommandImpl.java, fabric/src/main/java/net/mehvahdjukaar/supplementaries/reg/fabric/ModArgumentsImpl.java, forge/src/main/java/net/mehvahdjukaar/supplementaries/reg/forge/ModArgumentsImpl.java
Port record-song command to fabric, ensure its functionality same with that on forge.
Instead of re-invent EnumArgument on fabric, two ad-hoc argument classes are added, like vanilla GameModeArgument.
No matter any approach we used, registering ArgumentTypeInfo is still needed.
Tested on fabric, including:
- "/supplementaries record"  -- complaint
- "/supplementaries record start"  -- complaint
- "/supplementaries record start NOTE_BLOCKS BASS"  -- start recording
- "/supplementaries record start NOTE_BL 111"  -- complaint "Source must be one of [NOTE_BLOCKS, SOUND_EVENTS], found NOTE_BL"
- "/supplementaries record stop "  -- stop recording
- "/supplementaries record stop 661 0"  -- stop recording
Not test on forge, can't get minecraft launched even before the change...
=> Port record-song command to fabric, and adding corrsponding en-us zh-cn zh-tw translations

common/src/main/java/net/mehvahdjukaar/supplementaries/integration/JEICompat.java
Should correctly display only the recipes  for red bunting when pressing `R` in JEI hovering over red bunting for example.
Could sadly not try it out tho, because I could not get the project to run locally
=> add IIngredientSubtypeInterpreter for buntings

common/src/main/resources/data/supplementaries/loot_table/blocks/urn_loot/epic.json, common/src/main/resources/data/supplementaries/loot_table/blocks/urn_loot/rare.json, common/src/main/resources/data/supplementaries/loot_table/blocks/urn_loot/urn_loot.json, common/src/main/resources/data/supplementaries/loot_table/inject/end_city_stasis.json, common/src/main/resources/data/supplementaries/loot_table/inject/temple_spikes.json, common/src/main/resources/data/supplementaries/loot_table/inject/test.json
Notes:
* Had to use a generic map marker decoration since `supplementaries:igloo` doesn't exist on 1.21 yet on `supplementaries:inject/test`
=> Update loot tables to 1.21

common/src/main/java/net/mehvahdjukaar/supplementaries/ArclightMixinPlugin.java, common/src/main/java/net/mehvahdjukaar/supplementaries/mixins/CreeperArclightMixin.java, common/src/main/resources/mixins.arclight.json, common/src/main/resources/supplementaries-common.mixins.json
I've added MixinPlugin which tries to load Arclight mixin Class. And if it does, then it uses special mixin (because Arclight overwrites target mixin). If it doesn't - it loads base Class.
=> Arclight server compatibility fix

common/src/main/resources/data/supplementaries/tags/items/lunch_basket_blacklist.json
* Sets all items within the tag to `"required": false` to prevent breaking the tag if items do not exist
=> Prevents lunch_basket_blacklist.json item tag from being "cooked"

build.gradle, common/build.gradle, common/src/main/java/net/mehvahdjukaar/supplementaries/common/items/SackItem.java, common/src/main/java/net/mehvahdjukaar/supplementaries/common/items/SafeItem.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/CompatHandler.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/ShulkerBoxTooltipCompat.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/shulkerboxtooltip/SackPreviewProvider.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/shulkerboxtooltip/SafePreviewProvider.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/shulkerboxtooltip/VariableSizePreviewRenderer.java, fabric/build.gradle, fabric/src/main/java/net/mehvahdjukaar/supplementaries/integration/fabric/ShulkerBoxTooltipCompatImpl.java, fabric/src/main/resources/fabric.mod.json, forge/build.gradle, forge/src/main/java/net/mehvahdjukaar/supplementaries/forge/SupplementariesForge.java, forge/src/main/java/net/mehvahdjukaar/supplementaries/integration/forge/QuarkClientCompatImpl.java, forge/src/main/java/net/mehvahdjukaar/supplementaries/integration/forge/ShulkerBoxTooltipCompatImpl.java, gradle.properties
Added ShulkerBoxTooltip plugin to enable previews for safes and sacks. The preview functionality overrides the one from Quark when both mods are present.
This targets Minecraft 1.20.1 for now, I will work on 1.21 if this PR is accepted.
Added preview : only shows up when the player is allowed to open the safe.
Added preview support with special handling of varying stack inventory size.
I suspect that the newly added rendering code in `VariableSizePreviewRenderer` will not survive a port to 1.20.6. Don't hesitate to ask me if you want support for that version as well.
**Orignal issue:** https://github.com/MisterPeModder/ShulkerBoxTooltip/issues/150
=> Add ShulkerBoxTooltip Compatibility

build.gradle, common/build.gradle, common/src/main/java/net/mehvahdjukaar/supplementaries/common/block/tiles/SafeBlockTile.java, common/src/main/java/net/mehvahdjukaar/supplementaries/common/items/SackItem.java, common/src/main/java/net/mehvahdjukaar/supplementaries/common/items/SafeItem.java, common/src/main/java/net/mehvahdjukaar/supplementaries/common/items/components/SafeOwner.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/CompatHandler.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/ShulkerBoxTooltipCompat.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/shulkerboxtooltip/SackPreviewProvider.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/shulkerboxtooltip/SafePreviewProvider.java, common/src/main/java/net/mehvahdjukaar/supplementaries/integration/shulkerboxtooltip/VariableSizePreviewRenderer.java, fabric/build.gradle, fabric/src/main/java/net/mehvahdjukaar/supplementaries/integration/fabric/ShulkerBoxTooltipCompatImpl.java, fabric/src/main/resources/fabric.mod.json, gradle.properties, neoforge/build.gradle, neoforge/src/main/java/net/mehvahdjukaar/supplementaries/integration/neoforge/QuarkClientCompatImpl.java, neoforge/src/main/java/net/mehvahdjukaar/supplementaries/integration/neoforge/ShulkerBoxTooltipCompatImpl.java, neoforge/src/main/java/net/mehvahdjukaar/supplementaries/neoforge/SupplementariesForge.java
Like PR #1339, this adds ShulkerBoxTooltip compatibility for the 1.21 branch.
This fixes a bug in the serialization of the SafeOwner component where the owner name and password would get swapped.
=> Add ShulkerBoxTooltip Compatibility (1.21.1)

common/src/main/java/net/mehvahdjukaar/supplementaries/common/block/tiles/BlackboardBlockTile.java
Firstly, this PR fixes a bug when input string is too large (possible ArrayIndexOutOfBoundsException and server crash)
https://github.com/MehVahdJukaar/Supplementaries/blob/d7d31879e057fc95c200fcf39430e763b83ee827/common/src/main/java/net/mehvahdjukaar/supplementaries/common/block/tiles/BlackboardBlockTile.java#L176
Secodly, it introduces a new encoding which is backwards compatible with monochrome encoding.
Here's a brief description of the encoding:
Encoding a monochrome image is achieved with the same(64 symbols) encoding, so it's backwards compatible.
Encoding a colored image is achieved by adding 64 more symbols ("Color mask")
So symbols 1-64 represents which pixels are going to be non-black, and symbols 64-128 represents the color of pixels (in the same format as in 1.16.5 version) …
=> Improve display link blackboard encoding

common/src/main/java/net/mehvahdjukaar/supplementaries/common/items/crafting/SoapClearRecipe.java, common/src/main/java/net/mehvahdjukaar/supplementaries/common/items/crafting/SpecialRecipeDisplays.java, common/src/main/java/net/mehvahdjukaar/supplementaries/common/utils/SoapWashableHelper.java, common/src/main/java/net/mehvahdjukaar/supplementaries/reg/ModTags.java
Add additional checks against an blacklist item/block tag for soap functionalities.
Since the recipes could have an input which is a tag itself instead of a list of items, this means that the check is actually done against the output item. Sounds counterintuitive at first, but since mod authors will add all of the colored variants to the tag, it will also work since the "white" variant should also be in there
=> add item/block tags to blacklist items from being cleaned with soap

common/src/main/resources/data/supplementaries/tags/item/hourglass_dusts.json
`create:powdered_obsidian` was in the tag twice
=> [1.21] Remove duplicate entry in #supplementaries:hourglass_dusts

common/src/main/resources/data/supplementaries/tags/items/hourglass_dusts.json
`#forge:dusts` and `create:powdered_obsidian` were each in the tag twice
=> [1.20.1] Remove duplicate entries in #supplementaries:hourglass_dusts

common/src/main/java/net/mehvahdjukaar/supplementaries/common/block/blocks/TrappedPresentBlock.java
Fixes issue where trapped presents could only lightUp if they were *already* isLitUp, effectively meaning they could only be set off directly by a player rather than via gunpowder or redstone.
=> Trapped present detonation fix

common/src/main/resources/data/supplementaries/catchable_mobs_properties/betteranimalsplus_flying_fish.json
Removed extra `+` sign that causes errors in logs.
Fixes this error:
```log
[Worker-ResourceReload-3/ERROR] [net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener/]: Couldn't parse data file supplementaries:betteranimalsplus_flying_fish from supplementaries:catchable_mobs_properties/betteranimalsplus_flying_fish.json
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 2 column 38 path $.render_fluid
at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.GsonHelper.fromNullableJson(GsonHelper.java:527) ~[client-1.21.1-20240808.144430-srg.jar%23492!/:?]
at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.GsonHelper.fromJson(GsonHelper.java:532) …
```
=> Fix `betteranimalsplus_flying_fish.json`

common/src/main/java/net/mehvahdjukaar/supplementaries/common/block/blocks/FlowerBoxBlock.java
Fixes issue where the tooltip for flower boxes (which describes their simple-mode functionality) is only shown if they *aren't* set to simple mode
=> Fix flower box tooltip

common/src/main/java/net/mehvahdjukaar/supplementaries/integration/shulkerboxtooltip/SackPreviewProvider.java
This fixes a crash where the initializer of `SackPreviewProvider#RENDERER` would run on dedicated servers (despite the `@Environment` annotation :disappointed:), causing the client-only `PreviewRenderer` class to load.
Closes https://github.com/MisterPeModder/ShulkerBoxTooltip/issues/200
=> fix shulkerboxtooltip crashing on dedicated servers (1.21)

common/src/main/java/net/mehvahdjukaar/supplementaries/integration/shulkerboxtooltip/SackPreviewProvider.java
This fixes a crash where the initializer of `SackPreviewProvider#RENDERER` would run on dedicated servers (despite the `@Environment` annotation :disappointed:), causing the client-only `PreviewRenderer` class to load.
Closes https://github.com/MisterPeModder/ShulkerBoxTooltip/issues/200
=> fix shulkerboxtooltip crashing on dedicated servers (1.20.1)

common/src/main/resources/data/supplementaries/tags/potion/tipped_spikes_blacklist.json
This modifies the tipped_spikes_blacklist tag to make make vanilla status effects optional. These status effects were only introduced in 1.20.5. This means loading this tag fails silently in 1.20.1 builds of Supplementaries.
=> Make vanilla status effects optional in tipped_spikes_blacklist

common/build.gradle, common/src/main/java/net/mehvahdjukaar/supplementaries/common/block/tiles/CannonBlockTile.java, fabric/build.gradle, fabric/src/main/java/net/mehvahdjukaar/supplementaries/integration/fabric/CCCompatImpl.java, neoforge/build.gradle, neoforge/src/main/java/net/mehvahdjukaar/supplementaries/integration/neoforge/CCCompatImpl.java
Add a cannon peripheral with 7 functions:
- `void setYaw(double)` Sets yaw of the cannon and sends an update to players
- `double getYaw()` Gets yaw of the cannon
- `void setPitch(double)` Ditto 1
- `double getPitch()` Ditto 2
- `void setPower(int)` Ditto 1
- `double getPower()` Ditto 2
- `void ignite()` Shoots the cannon
=> Add a Cannon peripheral
